ema_blog_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: EmaBlogBundle:Default:index }

EmaBlogBundle_post:
    resource: "@EmaBlogBundle/Resources/config/routing/post.yml"
    prefix:   /post

#index:
#    pattern: /
#    defaults: { _controller: EmaBlogBundle:Blog:index }

#index:
#    pattern: /list
#    defaults: { _controller: EmaBlogBundle:Blog:list }

#post:
#    pattern: /post/{id}
#    defaults: { _controller: EmaBlogBundle:Blog:post }

#edit:
#    pattern: /edit/{id}
#    defaults: { _controller: EmaBlogBundle:Blog:edit , id: 0}
