ema_blog_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: EmaBlogBundle:Default:index }

index:
    pattern: /
    defaults: { _controller: EmaBlogBundle:Blog:index }

index:
    pattern: /list
    defaults: { _controller: EmaBlogBundle:Blog:list }


post:
    pattern: /post/{id}
    defaults: { _controller: EmaBlogBundle:Blog:post }
