parameters:
#    ema_blog.example.class: Ema\BlogBundle\Example

services:
#    ema_blog.example:
#        class: %ema_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
